### ISSUE TITLE
`message.forward(room)` results in a invalid official message being forwarded.

### ISSUE THREAD

**Issue by huan** [juzibot/donut-tester#21]
Reproduce steps:

1. A `user` forward an Official Account message to the `bot`
1. the `bot` get a `message` instance from the `on(message, ...)` event
1. bot call `message.forward(room)`, which the room is a Room instance.
1. the message was forwarded to the room, however, it can not be opened with an error message: "参数错误"

**Comment by su-chang** [comment]
Thanks for the issue.

It has be fixed in `wechaty-puppet-donut@0.3.61`

**Comment by huan** [comment]
Awesome, thank you very much for the fix!

**Comment by huan** [comment]
Close this issue because it's confirmed fixed.
