### ISSUE TITLE
Event 'room-leave' CAN'T touch off

### ISSUE THREAD

**Issue by why2lyj** [juzibot/donut-tester#39]
> Important：Please file the issue follow the template, or we won't help you to solve the problem.

## 1. Versions
- What is your wechaty version?
Answer: python-wechaty:0.6.7, python-puppet:0.0.16, python-puppet-hostie:0.2.12

- What is your wechaty-puppet-donut version?
Answer: as above 

- What is your node version? (run `node --version`)
Answer: without node

- What os are you using
Answer: Window7 and docker images python3.7-slim

## 2. Describe the bug

Event 'room-join' can't touch off 

## 3. To Reproduce

```python
bot = Wechaty().on('room-leave', xxx_function)
await bot.start()
```

## 7. Additional context

after Wechat PC client upgrade, this event can't touch off anymore

[bug]

**Comment by su-chang** [comment]
Sorry, I can not reproduce this issue, could you please test it in typescript wechaty?
