### ISSUE TITLE
WARN Puppet dogReset() reason: {"data":"onGrpcStreamEvent(EVENT_TYPE_LOGIN)","timeout":60000}

### ISSUE THREAD

**Issue by tomallv** [juzibot/donut-tester#53]
Today, i instead the padplus token by donut token, just modified the main function (.js file ) follow by the example from https://github.com/juzibot/donut-tester as bellow:

=========================================================
const { Wechaty } = require("wechaty") // Wechaty核心包
const config = require("./config") // 配置文件

const onScan = require("./onScan") // 机器人需要扫描二维码时监听回调
const onRoomJoin = require("./onRoomJoin") // 加入房间监听回调
const onMessage = require("./onMessage") // 消息监听回调
const onFriendShip = require("./onFriendShip") // 好友添加监听回调

const token = config.token

// 初始化
const bot = new Wechaty({
  puppet: "wechaty-puppet-hostie",
  puppetOptions: {token,}
})

bot
  .on("scan", onScan) // 机器人需要扫描二维码时监听
  .on("room-join", onRoomJoin) // 加入房间监听
  .on("message", onMessage(bot)) // 消息监听
  .on("friendship", onFriendShip) // 好友添加监听
  .start()
=========================================================

On the 1st time to  start, it works well. I can login var QRcode, the info of windows client has been login shown on the phone  and also received the message from "Bot Setry" on wechat client. 

Under this case, i sent several wechat message to bot, it works well. And then i use my ex-wechat account create a room and add bot, sent message in the room via my ex-wechat account, no response on bot. wait about 2-3 mins, the waring "WARN Puppet dogReset() reason: {"data":"onGrpcStreamEvent(EVENT_TYPE_LOGIN)","timeout":60000}
" pops up. 

i restart bot, got the same issue. So i logout the windows cline from my phone. and restart bot, unfortunately no login qr-code pops up, and get the same waring info as below screenshot:

![image](https://user-images.githubusercontent.com/33150898/99942792-3104fc80-2dab-11eb-9bce-02a78313252d.png)

version info:
    "qrcode-terminal": "^0.12.0",
    "request": "^2.88.2",
    "urlencode": "^1.1.0",
    "wechaty": "^0.51.1",
    "wechaty-puppet": "^0.32.3",

please help me to check where is wrong? thanks!

**Comment by su-chang** [comment]
Thank you for your issue, please contact with `juzibot` and send your token to him. We will check it after that.

**Comment by tomallv** [comment]
OK, i have contacted with juzibot with offering my donut token, please help to check, thanks a lot!

**Comment by su-chang** [comment]
If there's no problem any more, please feel free to close it, thank you.

**Comment by tomallv** [comment]
This issue had been resolved via juzibot, due to the exception during the resource allocation in server side. I will keep one eye on this about one week, if it doesn't occurs again, i will close this.

**Comment by tomallv** [comment]
this is reproduced in this afternoon, and send the token and log to juzibot

**Comment by tomallv** [comment]
This issue was reproduced in this afternoon, and donut token has been sent to juzibot with logs. Under juzibot requests, i set WECHATY_LOG=silly.

**Comment by tomallv** [comment]
i haven't met this issue in last one week, so close it.

**Comment by sunshinearea** [comment]
@su-chang @tomallv  Hello, I have encountered the same problem. After successful startup login, the bot will automatically drop the line and automatically log in. May I ask how to deal with this problem?
