### ISSUE TITLE
No response for scan code login

### ISSUE THREAD

**Issue by zxypetre** [juzibot/donut-tester#54]
![image](https://user-images.githubusercontent.com/31026087/99943240-f18ae000-2dab-11eb-96d0-308b8ffb209b.png)
启动程序后，扫码，手机上点了确定但是程序还会继续推送二维码，手机上也没有登录提示。已经删除了node_modules和package-lock.json并重新下载

**Comment by PandaTsui** [comment]
me too

**Comment by su-chang** [comment]
@zxypetre 确认是否仍有问题，如果有，联系juzibot，如果没有问题，确认后请关闭issue，多谢。

**Comment by InfTkm** [comment]
有一模一样的问题，请问朋友如何解决这个问题的 
我明早会联系Juzibot进行确认

**Comment by jun951448356** [comment]
我刚刚拿到的测试token，遇到了同样的问题。你们解决了吗？

**Comment by su-chang** [comment]
联系juzibot，发送token给我们这边看下。

**Comment by zxypetre** [comment]
同样的问题请联系juzibot，发送token给我们这边看下。

**Comment by Adricz22** [comment]
Hello @juzibot 👋

# 🌍 Top International Developer Events

Discover the **most influential tech conferences and developer events** happening around the world.  
Connect, learn, and grow with the **global developer community**.

---

## 🚀 Why Join?
- 🔴 **Live Events** – Stay updated with the latest happenings in tech  
- 🌐 **Global Community** – Network with developers from all continents  
- 📅 **Updated Daily** – Fresh events, always current  
- 🏆 **Top 10 Developer Events** – Hand-picked to shape the future of technology  

From **cutting-edge frameworks** to **emerging paradigms**, we bring you the opportunities that matter.

---

## 🔑 Get Started  
**[➡️ Continue with GitHub](https://www.globaldevsummit.com/)**  
🔒 **Connect securely** • Save favorites • Get personalized recommendations  

---

## 📌 Highlights
- Meet industry leaders and tech innovators  
- Join exclusive technical workshops  
- Explore new frameworks, tools, and best practices  
- Grow your personal and professional network  

---

> 📢 **Tip:** Bookmark the page and check daily for new opportunities.  
Your next big career move could start here!

---
