### ISSUE TITLE
个人微信扫码并确认登录后没有反应

### ISSUE THREAD

**Issue by PandaTsui** [juzibot/donut-tester#55]
> Important：Please file the issue follow the template, or we won't help you to solve the problem.

## 0. Report Issue Guide

1. Please run the following command and check whether the problem has been fixed：
```
rm -rf package-lock.json
rm -rf node_modules
npm install
```

2. Please search in [FAQ List](https://wechaty.js.org/faq) first, and make sure your problem has not been solved before.

3. Please search in the issue first, and make sure your problem had not been reported before

## 1. Versions
- What is your wechaty version?
Answer: 0.51.1

- What is your wechaty-puppet-donut version?
Answer: "wechaty-puppet-hostie": "^0.11.10"

- What is your node version? (run `node --version`)
Answer:10.15.0

- What os are you using
Answer: win10 

## 2. Describe the bug
出现二维码，使用个人微信扫码后点击登录，但是实际并没有登录成功，还在反复出现新的二维码。

## 3. To Reproduce
This part is very important: if you can not provide any reproduce steps, then the problem will be very hard to be recognized.

1. npm install wechaty@next
2. npm install  wechaty-puppet-hostie@next
3. node ./index.js

## 4. Expected behavior
Give a clear and concise description of what you expected to happen.

## 5. Actual behavior
If applicable, add screenshots to help explain your problem. But do not paste log screenshots here.

## 6. Full Output Logs
Set env `WECHATY_LOG=silly` in order to set log level to silly, then we can get the full log (If you dosen't set log env, log level is info as default, we cannot get the full log)

**We need full log instead of log screenshot or log fragments!**

<details>
<summary>
Show Logs
</summary>

```shell
$ WECHATY_LOG=silly node yourbot.js

Question: Paste your FULL(DO NOT ONLY PROVIDE FRAGMENTS) log messages
Answer:

```

</details>

## 7. Additional context

[bug]

**Comment by su-chang** [comment]
尝试扫下新的二维码看看是否能登录成功呢？

如果还无法登录成功，请联系`juzibot`

**Comment by PandaTsui** [comment]
> 尝试扫下新的二维码看看是否能登录成功呢？
> 
> 如果还无法登录成功，请联系`juzibot`

不行哦，我每次扫码，并确认登录，都会弹出一个新的二维码，重复此动作。

**Comment by PandaTsui** [comment]
> 尝试扫下新的二维码看看是否能登录成功呢？
> 
> 如果还无法登录成功，请联系`juzibot`

可以了，我没做任何改动。不知道为什么，先关闭了
