### ISSUE TITLE
wss api.chatie.io return "payload": "0.0.0.0"

### ISSUE THREAD

**Issue by huangsong** [juzibot/donut-tester#6]
> Important：Please file the issue follow the template, or we won't help you to solve the problem.

## 0. Report Issue Guide

1. Please run the following command and check whether the problem has been fixed：
```
rm -rf package-lock.json
rm -rf node_modules
npm install
```

2. Please search in [FAQ List](https://wechaty.js.org/faq) first, and make sure your problem has not been solved before.

3. Please search in the issue first, and make sure your problem had not been reported before

## 1. Versions
- What is your wechaty version?
Answer:@latest

- What is your wechaty-puppet-donut version?
Answer:

- What is your node version? (run `node --version`)
Answer: v10.20.1

- What os are you using
Answer: win10

## 2. Describe the bug
Give a clear and concise description of what the bug is.

## 3. To Reproduce
This part is very important: if you can not provide any reproduce steps, then the problem will be very hard to be recognized.

1. run 'node bot.js'
2. ...
3. ...

## 4. Expected behavior
Give a clear and concise description of what you expected to happen.

## 5. Actual behavior
If applicable, add screenshots to help explain your problem. But do not paste log screenshots here.

## 6. Full Output Logs
Set env `WECHATY_LOG=silly` in order to set log level to silly, then we can get the full log (If you dosen't set log env, log level is info as default, we cannot get the full log)

**We need full log instead of log screenshot or log fragments!**

<details>
<summary>

</summary>

```shell
16:06:07 ERR PuppetHostie start() rejection: no endpoint
Error: no endpoint
    at PuppetHostie.<anonymous> (D:\Work\github\wechaty-getting-started\node_modules\wechaty-puppet-hostie\dist\src\client\puppet-hostie.js:85:27)
    at Generator.next (<anonymous>)
    at fulfilled (D:\Work\github\wechaty-getting-started\node_modules\wechaty-puppet-hostie\dist\src\client\puppet-hostie.js:5:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
16:06:07 ERR Wechaty start() exception: no endpoint
Bot error: Error: no endpoint
    at PuppetHostie.<anonymous> (D:\Work\github\wechaty-getting-started\node_modules\wechaty-puppet-hostie\dist\src\client\puppet-hostie.js:85:27)
    at Generator.next (<anonymous>)
    at fulfilled (D:\Work\github\wechaty-getting-started\node_modules\wechaty-puppet-hostie\dist\src\client\puppet-hostie.js:5:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
16:06:07 WARN PuppetHostie stop() is called on a OFF puppet. await ready(off) and return.
16:06:07 INFO Wechaty <wechaty-puppet-hostie> stop() v0.38.4 is stoping ...
Waiting for the debugger to disconnect...

Process finished with exit code 0

```

</details>

## 7. Additional context

[bug] wss return
```
 {
  "name": "hostie",
  "payload": "0.0.0.0"
}
```

**Comment by huan** [comment]
That's because your windows token are offlined.

Contact JuziBOT to get a fix for that.
