### ISSUE TITLE
UNIMPLEMENTED: RPC method not implemented /wechaty.Puppet/Start

### ISSUE THREAD

**Issue by dchaofei** [juzibot/donut-tester#7]
> Important：Please file the issue follow the template, or we won't help you to solve the problem.

## 0. Report Issue Guide

1. Please run the following command and check whether the problem has been fixed：
```
rm -rf package-lock.json
rm -rf node_modules
npm install
```

2. Please search in [FAQ List](https://wechaty.js.org/faq) first, and make sure your problem has not been solved before.

3. Please search in the issue first, and make sure your problem had not been reported before

## 1. Versions
- What is your wechaty version?
Answer:

- What is your wechaty-puppet-donut version?
Answer:

- What is your node version? (run `node --version`)
Answer:

- What os are you using
Answer:

## 2. Describe the bug
Give a clear and concise description of what the bug is.

## 3. To Reproduce
This part is very important: if you can not provide any reproduce steps, then the problem will be very hard to be recognized.

1. run '...'
2. ...
3. ...

## 4. Expected behavior
Give a clear and concise description of what you expected to happen.

## 5. Actual behavior
If applicable, add screenshots to help explain your problem. But do not paste log screenshots here.

## 6. Full Output Logs
Set env `WECHATY_LOG=silly` in order to set log level to silly, then we can get the full log (If you dosen't set log env, log level is info as default, we cannot get the full log)

**We need full log instead of log screenshot or log fragments!**

<details>
<summary>
Show Logs
</summary>

```shell
~/work/wechaty-puppet-hostie on  master! ⌚ 13:21:39
$ ts-node examples/ding-dong-bot.ts

Puppet Version: Puppet#0<PuppetHostie>()@0.7.1

Please wait... I'm trying to login in...


161.189.112.252:8788
13:21:48 ERR PuppetHostie start() rejection: 12 UNIMPLEMENTED: RPC method not implemented /wechaty.Puppet/Start
Bot start() fail: Error: 12 UNIMPLEMENTED: RPC method not implemented /wechaty.Puppet/Start
    at Object.exports.createStatusError (/Users/dingchaofei/work/wechaty-puppet-hostie/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/Users/dingchaofei/work/wechaty-puppet-hostie/node_modules/grpc/src/client_interceptors.js:1209:28)
    at InterceptingListener._callNext (/Users/dingchaofei/work/wechaty-puppet-hostie/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/Users/dingchaofei/work/wechaty-puppet-hostie/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/Users/dingchaofei/work/wechaty-puppet-hostie/node_modules/grpc/src/client_interceptors.js:847:24) {
  code: 12,
  metadata: Metadata { _internal_repr: {}, flags: 0 },
  details: 'RPC method not implemented /wechaty.Puppet/Start'
}
13:21:48 WARN PuppetHostie stop() is called on a OFF puppet. await ready(off) and return.

```

</details>

## 7. Additional context
github.com/chatie/grpc The `proto` library has recently been adjusted, so the server should use the latest` proto`, and now the client will report an error if it uses the latest `proto`.

[bug]

**Comment by huan** [comment]
@dchaofei This issue is related to our PR at https://github.com/Chatie/grpc/pull/49 , which actually was introduced by yourself. ;-)

The reason for this problem is that the GRPC package name was changed between versions.

To get it worked, please upgrade the Wechaty to the newest version (0.39.5 or above) then I believe this issue will be solved.

**Comment by dchaofei** [comment]
The server can fix this problem by using the latest Chatie/grpc. :smiley:

**Comment by su-chang** [comment]
When we update `wechaty` to `v0.39.5`, this bug has been fixed.

Thank you very much. @huan @dchaofei
